name: Lighthouse CI
on:
  push:
    branches:
      - main
      - master
    paths-ignore:
      - 'reports/**'  # 忽略报告目录的更改，防止循环触发
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

# 添加权限配置
permissions:
  contents: write
  pages: write

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # 更新到 Node.js 18

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y wget gnupg2
          wget -q https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt-get install -y ./google-chrome-stable_current_amd64.deb
          google-chrome --version

      - name: Install dependencies
        run: |
          npm init -y
          npm install -g @lhci/cli@0.12.x
          echo "node_modules/" > .gitignore
          echo ".lighthouseci/" >> .gitignore
          echo "*.deb" >> .gitignore

      - name: Run Lighthouse and Process Reports
        run: |
          mkdir -p reports
          NOW=$(date -u +"%Y-%m-%dT%H:%M:%S")
          
          echo "Cleaning reports directory..."
          rm -rf reports/*
          
          # 运行桌面版测试
          echo "Running Desktop test..."
          lhci collect \
            --url https://www.fadada.com \
            --settings.preset=desktop \
            --settings.chromeFlags="--no-sandbox --headless=new --disable-gpu" \
            --settings.maxWaitForLoad=30000 \
            --output=json \
            --outDir=.lighthouseci \
            --numberOfRuns=1

          # 运行移动版测试
          echo "Running Mobile test..."
          lhci collect \
            --url https://www.fadada.com \
            --settings.formFactor=mobile \
            --settings.screenEmulation.mobile=true \
            --settings.screenEmulation.width=360 \
            --settings.screenEmulation.height=640 \
            --settings.screenEmulation.deviceScaleFactor=2 \
            --settings.chromeFlags="--no-sandbox --headless=new --disable-gpu" \
            --settings.maxWaitForLoad=30000 \
            --output=json \
            --outDir=.lighthouseci \
            --numberOfRuns=1

          echo "Processing Lighthouse results..."
          echo "Files in .lighthouseci:"
          ls -la .lighthouseci/
          
          # 处理所有JSON报告文件
          found_desktop=false
          found_mobile=false
          
          for file in .lighthouseci/*.json; do
            if [ -f "$file" ]; then
              echo "Analyzing report: $file"
              content=$(cat "$file")
              if echo "$content" | grep -q "\"formFactor\": \"mobile\""; then
                device_type="mobile"
                found_mobile=true
              else
                device_type="desktop"
                found_desktop=true
              fi
              
              echo "Processing ${device_type} report..."
              
              # 复制并处理报告
              new_file="./reports/$(basename "${file%.json}")-${device_type}.json"
              cp "$file" "$new_file"
              DEVICE_TYPE=$device_type DATE_WITH_TIME=$NOW node process-report.js "$new_file"
              
              # 复制HTML报告
              html_file="${file%.json}.html"
              if [ -f "$html_file" ]; then
                cp "$html_file" "./reports/$(basename "${html_file%.html}")-${device_type}.html"
              fi
            fi
          done

          if ! $found_desktop; then
            echo "Warning: No desktop report was generated!"
          fi
          if ! $found_mobile; then
            echo "Warning: No mobile report was generated!"
          fi
          
          if ! $found_desktop && ! $found_mobile; then
            echo "Error: No reports were generated at all!"
            exit 1
          fi

      - name: List Reports Directory
        run: |
          echo "Contents of reports directory:"
          ls -la ./reports/

      - name: Cleanup and Prepare
        run: |
          rm -f google-chrome-stable_current_amd64.deb
          rm -rf .lighthouseci

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          
          # 添加所有报告文件
          git add reports/*.json reports/*.html || true
          git add .gitignore || true
          
          echo "Files staged for commit:"
          git diff --staged --name-status
          
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update Lighthouse reports $(date -u)"
            git push origin HEAD:${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}