name: Lighthouse CI
on:
  push:
    branches:
      - main
      - master
    paths-ignore:
      - 'reports/**'  # 忽略报告目录的更改，防止循环触发
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

# 添加权限配置
permissions:
  contents: write
  pages: write

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # 更新到 Node.js 18

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y wget gnupg2
          wget -q https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt-get install -y ./google-chrome-stable_current_amd64.deb
          google-chrome --version

      - name: Install dependencies
        run: |
          npm init -y
          npm install -g @lhci/cli@0.12.x
          echo "node_modules/" > .gitignore
          echo ".lighthouseci/" >> .gitignore
          echo "*.deb" >> .gitignore

      - name: Run Lighthouse and Process Reports
        run: |
          mkdir -p reports
          NOW=$(date -u +"%Y-%m-%dT%H:%M:%S")
          DATE=$(date -u +"%Y-%m-%d")
          
          # Create directories
          mkdir -p .lighthouseci/{desktop,mobile}
          
          # Run Desktop test with modified settings
          echo "Running Desktop test..."
          lhci collect \
            --url https://www.fadada.com \
            --settings.formFactor=desktop \
            --settings.screenEmulation.mobile=false \
            --settings.screenEmulation.width=1350 \
            --settings.screenEmulation.height=940 \
            --settings.screenEmulation.deviceScaleFactor=1 \
            --settings.chromeFlags="--no-sandbox --headless=new --disable-gpu" \
            --settings.maxWaitForLoad=30000 \
            --output=json \
            --outDir=.lighthouseci/desktop \
            --numberOfRuns=1

          # Run Mobile test
          echo "Running Mobile test..."
          lhci collect \
            --url https://www.fadada.com \
            --settings.formFactor=mobile \
            --settings.screenEmulation.mobile=true \
            --settings.screenEmulation.width=360 \
            --settings.screenEmulation.height=640 \
            --settings.screenEmulation.deviceScaleFactor=2 \
            --settings.chromeFlags="--no-sandbox --headless=new --disable-gpu" \
            --settings.maxWaitForLoad=30000 \
            --output=json \
            --outDir=.lighthouseci/mobile \
            --numberOfRuns=1

          # Process reports and update history
          process_report() {
            local device=$1
            local json_file=$(ls .lighthouseci/$device/lhr-*.json 2>/dev/null | head -n 1)
            
            if [ -n "$json_file" ]; then
              echo "Processing $device report: $json_file"
              
              # Copy reports
              cp "$json_file" "./reports/data-https___www_fadada_com_${device}-${DATE}.json"
              cp "${json_file%.json}.html" "./reports/data-https___www_fadada_com_${device}-${DATE}.html"
              
              # Process report and return the JSON data
              DEVICE_TYPE=$device DATE=$DATE DATE_WITH_TIME=$NOW \
              node process-report.js "./reports/data-https___www_fadada_com_${device}-${DATE}.json"
              
              return 0
            fi
            return 1
          }

          # Initialize or reset history.json
          echo '{"reports":[]}' > reports/history.json

          # Get processed data
          desktop_data=$(process_report "desktop")
          mobile_data=$(process_report "mobile")

          # Update history.json with new entry
          jq --arg date "$NOW" \
             --arg url "https://www.fadada.com" \
             --argjson desktop "$desktop_data" \
             --argjson mobile "$mobile_data" \
             '.reports += [{
                "date": $date,
                "url": $url,
                "desktop": $desktop,
                "mobile": $mobile
              }]' \
             reports/history.json > reports/history.json.tmp && mv reports/history.json.tmp reports/history.json

          # List final results
          echo "=== Final Results ==="
          echo "Reports generated:"
          ls -l reports/

      - name: List Reports Directory
        run: |
          echo "Contents of reports directory:"
          ls -la ./reports/

      - name: Cleanup and Prepare
        run: |
          rm -f google-chrome-stable_current_amd64.deb
          rm -rf .lighthouseci

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          
          echo "=== Git Status Before Add ==="
          git status
          
          # 使用find命令添加文件
          echo "Adding report files..."
          find reports -type f -name "data-https___www_fadada_com_*.json" -exec git add {} \; || true
          find reports -type f -name "data-https___www_fadada_com_*.html" -exec git add {} \; || true
          
          # 添加history.json如果存在
          if [ -f "reports/history.json" ]; then
            git add reports/history.json
          fi
          
          git add .gitignore || true
          
          echo "=== Files staged for commit ==="
          git status --short
          
          # 检查是否有文件要提交
          if git diff --cached --quiet; then
            echo "No changes to commit"
            exit 0
          else
            git commit -m "Update Lighthouse reports $(date -u)"
            git push origin "HEAD:$GITHUB_REF" || git push origin "HEAD:${GITHUB_REF#refs/heads/}"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}