name: Run Lighthouse CI

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *' # 每天凌晨 3 点自动运行

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Run Lighthouse CI on www.fadada.com
        uses: treosh/lighthouse-ci-action@v9
        with:
          urls: "https://www.fadada.com"
          configPath: ".lighthouserc.json"
