name: Lighthouse CI
on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # 更新到 Node.js 18

      - name: Install Chrome
        run: |
          wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/sources.list.d/google.list'
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Install dependencies
        run: |
          npm install -g @lhci/cli@0.12.x
          npm install fs path

      - name: Run Lighthouse and Process Reports
        run: |
          chmod +x process-report.js
          
          NOW=$(date -u +"%Y-%m-%dT%H:%M:%S")
          
          # 使用更稳定的配置运行 Lighthouse
          lhci collect \
            --url https://www.fadada.com \
            --settings.preset=desktop \
            --settings.chromeFlags="--no-sandbox --headless=new --disable-gpu" \
            --settings.maxWaitForLoad=30000 \
            --output=json \
            --outDir=./reports
          
          # 处理生成的报告
          for f in ./reports/lighthouse-*.json; do
            if [ -f "$f" ]; then
              echo "Processing report: $f"
              DATE_WITH_TIME=$NOW node process-report.js "$f"
            fi
          done

      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add reports/
          git commit -m "Update Lighthouse report $(date -u)"
          git push