name: Lighthouse CI
on:
  push:
    branches:
      - main
      - master
    paths-ignore:
      - 'reports/**'  # 忽略报告目录的更改，防止循环触发
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

# 添加权限配置
permissions:
  contents: write
  pages: write

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      # 添加缓存步骤
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            node_modules
            ~/cache/google-chrome-stable_current_amd64.deb
          key: ${{ runner.os }}-node-chrome-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-chrome-
            ${{ runner.os }}-node-
            ${{ runner.os }}-

      - name: Install Chrome
        run: |
          CHROME_DEB="google-chrome-stable_current_amd64.deb"
          CHROME_CACHE=~/cache/$CHROME_DEB
          
          if [ ! -f "$CHROME_CACHE" ]; then
            echo "Chrome not found in cache, downloading..."
            sudo apt-get update
            sudo apt-get install -y wget gnupg2
            wget -q https://dl.google.com/linux/direct/$CHROME_DEB
            mkdir -p ~/cache
            cp $CHROME_DEB $CHROME_CACHE
          else
            echo "Using cached Chrome package..."
            cp $CHROME_CACHE $CHROME_DEB
          fi
          
          sudo apt-get install -y ./$CHROME_DEB
          google-chrome --version

      - name: Install dependencies
        run: |
          # 如果没有package.json，使用已创建的版本
          if [ ! -f "package.json" ]; then
            cp .github/workflows/package.json ./package.json
          fi
          
          # 安装依赖并生成package-lock.json
          npm install
          
          # 更新gitignore
          echo "node_modules/" > .gitignore
          echo ".lighthouseci/" >> .gitignore
          echo "*.deb" >> .gitignore
          
          # 显示安装的版本
          npx lighthouse --version

      - name: Run Lighthouse and Process Reports
        run: |
          mkdir -p reports
          NOW=$(date -u +"%Y-%m-%dT%H:%M:%S")
          DATE=$(date -u +"%Y-%m-%d")
          
          # 不再清理reports目录
          # echo "Cleaning reports directory..."
          # rm -rf reports/*
          
          # 运行桌面版测试
          echo "Running Desktop test..."
          lhci collect \
            --url https://www.fadada.com \
            --settings.preset=desktop \
            --settings.chromeFlags="--no-sandbox --headless=new --disable-gpu" \
            --settings.maxWaitForLoad=30000 \
            --output=json \
            --outDir=.lighthouseci \
            --numberOfRuns=1

          # 运行移动版测试
          echo "Running Mobile test..."
          lhci collect \
            --url https://www.fadada.com \
            --settings.formFactor=mobile \
            --settings.screenEmulation.mobile=true \
            --settings.screenEmulation.width=360 \
            --settings.screenEmulation.height=640 \
            --settings.screenEmulation.deviceScaleFactor=2 \
            --settings.chromeFlags="--no-sandbox --headless=new --disable-gpu" \
            --settings.maxWaitForLoad=30000 \
            --output=json \
            --outDir=.lighthouseci \
            --numberOfRuns=1

          echo "Processing Lighthouse results..."
          echo "Files in .lighthouseci:"
          ls -la .lighthouseci/
          
          # 处理所有JSON报告文件
          found_desktop=false
          found_mobile=false
          
          for file in .lighthouseci/*.json; do
            if [ -f "$file" ]; then
              echo "Analyzing report: $file"
              content=$(cat "$file")
              if echo "$content" | grep -q "\"formFactor\": \"mobile\""; then
                device_type="mobile"
                found_mobile=true
                # 生成带时间戳的文件名
                new_json="./reports/data-https___www_fadada_com_${device_type}-${DATE}.json"
                new_html="./reports/data-https___www_fadada_com_${device_type}-${DATE}.html"
              else
                device_type="desktop"
                found_desktop=true
                # 生成带时间戳的文件名
                new_json="./reports/data-https___www_fadada_com_${device_type}-${DATE}.json"
                new_html="./reports/data-https___www_fadada_com_${device_type}-${DATE}.html"
              fi
              
              # 复制并处理报告
              cp "$file" "$new_json"
              DEVICE_TYPE=$device_type DATE_WITH_TIME=$NOW node process-report.js "$new_json"
              
              # 复制HTML报告
              html_file="${file%.json}.html"
              if [ -f "$html_file"]; then
                cp "$html_file" "$new_html"
              fi
            fi
          done

          # 更新历史记录
          if [ ! -f "reports/history.json" ]; then
            echo '{"reports":[]}' > reports/history.json
          fi
          
          # 使用临时文件来更新history.json
          jq --arg date "$NOW" \
             --arg desktop_report "data-https___www_fadada_com_desktop-${DATE}.json" \
             --arg mobile_report "data-https___www_fadada_com_mobile-${DATE}.json" \
             '.reports += [{"date": $date, "desktop": $desktop_report, "mobile": $mobile_report}]' \
             reports/history.json > reports/history.json.tmp && mv reports/history.json.tmp reports/history.json

          # 验证报告是否生成
          echo "=== Report Status ==="
          echo "Desktop report found: $found_desktop"
          echo "Mobile report found: $found_mobile"
          echo "Reports directory contents:"
          ls -la ./reports/

      - name: List Reports Directory
        run: |
          echo "Contents of reports directory:"
          ls -la ./reports/

      - name: Cleanup and Prepare
        run: |
          rm -f google-chrome-stable_current_amd64.deb
          rm -rf .lighthouseci

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          
          echo "=== Git Status Before Add ==="
          git status
          
          # 使用find命令添加文件
          echo "Adding report files..."
          find reports -type f -name "data-https___www_fadada_com_*.json" -exec git add {} \; || true
          find reports -type f -name "data-https___www_fadada_com_*.html" -exec git add {} \; || true
          
          # 添加history.json如果存在
          if [ -f "reports/history.json" ]; then
            git add reports/history.json
          fi
          
          git add .gitignore || true
          
          echo "=== Files staged for commit ==="
          git status --short
          
          # 检查是否有文件要提交
          if git diff --cached --quiet; then
            echo "No changes to commit"
            exit 0
          else
            git commit -m "Update Lighthouse reports $(date -u)"
            git push origin "HEAD:$GITHUB_REF" || git push origin "HEAD:${GITHUB_REF#refs/heads/}"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}