name: Lighthouse CI
on:
  push:
    branches:
      - main
      - staging
      - release/*
    paths-ignore:
      - 'reports/**'  # 忽略报告目录的更改，防止循环触发
  schedule:
    - cron: '0 1,13 * * *'  # 北京时间9点和21点
  workflow_dispatch:

permissions:
  contents: write
  pages: write

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        site:
          - url: "https://www.fadada.com"
            name: "fadada"
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          npm init -y
          npm install -g @lhci/cli@0.12.x
          npm install fs-extra
          echo "node_modules/" > .gitignore
          echo ".lighthouseci/" >> .gitignore

      - name: Set date and branch env
        id: set_env
        run: |
          echo "REPORT_DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV
          echo "BRANCH_NAME=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Create reports directory
        run: mkdir -p reports/$REPORT_DATE/$BRANCH_NAME/${{ matrix.site.name }}

      # Run both desktop and mobile tests using Lighthouse CI
      - name: Create Lighthouse directories
        run: |
          # 确保输出目录存在
          mkdir -p .lighthouseci/desktop
          mkdir -p .lighthouseci/mobile
          ls -la .lighthouseci/

      - name: Run Lighthouse CI
        run: |
          # Create LHCI configuration file
          cat > lighthouserc.json << EOF
          {
            "ci": {
              "collect": {
                "settings": {
                  "maxWaitForLoad": 30000,
                  "skipAudits": []
                },
                "numberOfRuns": 1
              }
            }
          }
          EOF
          
          # Desktop
          echo "Running desktop tests..."
          mkdir -p .lighthouseci/desktop
          lhci collect \
            --url=${{ matrix.site.url }} \
            --settings.formFactor=desktop \
            --settings.screenEmulation.mobile=false \
            --settings.screenEmulation.width=1350 \
            --settings.screenEmulation.height=940 \
            --settings.screenEmulation.deviceScaleFactor=1 \
            --settings.chromeFlags="--no-sandbox --headless=new --disable-gpu" \
            --settings.output=json,html \
            --outDir=.lighthouseci/desktop
          
          # 检查是否生成了文件
          echo "Checking desktop output files..."
          find .lighthouseci/desktop -type f | sort
          
          # Mobile
          echo "Running mobile tests..."
          mkdir -p .lighthouseci/mobile
          lhci collect \
            --url=${{ matrix.site.url }} \
            --settings.formFactor=mobile \
            --settings.screenEmulation.mobile=true \
            --settings.screenEmulation.width=360 \
            --settings.screenEmulation.height=640 \
            --settings.screenEmulation.deviceScaleFactor=2 \
            --settings.chromeFlags="--no-sandbox --headless=new --disable-gpu" \
            --settings.output=json,html \
            --outDir=.lighthouseci/mobile
          
          # 检查是否生成了文件
          echo "Checking mobile output files..."
          find .lighthouseci/mobile -type f | sort
          
          # List all contents recursively to debug
          echo "All files in .lighthouseci:"
          find .lighthouseci -type f | xargs ls -la

      - name: Copy reports to reports directory
        run: |
          # Copy desktop reports
          echo "Finding desktop report files..."
          DESKTOP_JSON=$(find .lighthouseci -path "*/desktop/*.json" | grep -v "manifest.json" | sort -r | head -n 1)
          DESKTOP_HTML=$(find .lighthouseci -path "*/desktop/*.html" | sort -r | head -n 1)
          
          echo "Desktop JSON file: $DESKTOP_JSON"
          echo "Desktop HTML file: $DESKTOP_HTML"
          
          # Create target directory if it doesn't exist
          mkdir -p "reports/$REPORT_DATE/$BRANCH_NAME/${{ matrix.site.name }}"
          
          # Only copy if files exist
          if [ -n "$DESKTOP_JSON" ] && [ -f "$DESKTOP_JSON" ]; then
            cp "$DESKTOP_JSON" "reports/$REPORT_DATE/$BRANCH_NAME/${{ matrix.site.name }}/lhr-${{ matrix.site.name }}-desktop.report.json"
          else
            echo "Warning: Desktop JSON file not found"
          fi
          
          if [ -n "$DESKTOP_HTML" ] && [ -f "$DESKTOP_HTML" ]; then
            cp "$DESKTOP_HTML" "reports/$REPORT_DATE/$BRANCH_NAME/${{ matrix.site.name }}/lhr-${{ matrix.site.name }}-desktop.report.html"
          else
            echo "Warning: Desktop HTML file not found"
          fi
          
          # Copy mobile reports
          echo "Finding mobile report files..."
          MOBILE_JSON=$(find .lighthouseci -path "*/mobile/*.json" | grep -v "manifest.json" | sort -r | head -n 1)
          MOBILE_HTML=$(find .lighthouseci -path "*/mobile/*.html" | sort -r | head -n 1)
          
          echo "Mobile JSON file: $MOBILE_JSON"
          echo "Mobile HTML file: $MOBILE_HTML"
          
          # Only copy if files exist
          if [ -n "$MOBILE_JSON" ] && [ -f "$MOBILE_JSON" ]; then
            cp "$MOBILE_JSON" "reports/$REPORT_DATE/$BRANCH_NAME/${{ matrix.site.name }}/lhr-${{ matrix.site.name }}-mobile.report.json"
          else
            echo "Warning: Mobile JSON file not found"
          fi
          
          if [ -n "$MOBILE_HTML" ] && [ -f "$MOBILE_HTML" ]; then
            cp "$MOBILE_HTML" "reports/$REPORT_DATE/$BRANCH_NAME/${{ matrix.site.name }}/lhr-${{ matrix.site.name }}-mobile.report.html"
          else
            echo "Warning: Mobile HTML file not found"
          fi

      - name: Process reports (optimized format)
        run: |
          # 创建 process-report.js 文件，如果不存在
          if [ ! -f "process-report.js" ]; then
            cat > process-report.js << 'EOF'
            const fs = require('fs-extra');
            const path = require('path');
            
            // 获取命令行参数
            const reportFile = process.argv[2];
            const historyFile = process.argv[3];
            const siteUrl = process.argv[4];
            const date = process.argv[5];
            const device = process.argv[6];
            
            // 确保报告文件存在
            if (!fs.existsSync(reportFile)) {
              console.error(`Error: Report file ${reportFile} does not exist`);
              process.exit(1);
            }
            
            try {
              // 读取报告JSON
              const report = fs.readJsonSync(reportFile);
              
              // 提取关键数据
              const metrics = {
                date,
                device,
                url: siteUrl,
                scores: {
                  performance: report.categories.performance.score * 100,
                  accessibility: report.categories.accessibility.score * 100,
                  'best-practices': report.categories['best-practices'].score * 100,
                  seo: report.categories.seo.score * 100,
                },
                metrics: {
                  'first-contentful-paint': report.audits['first-contentful-paint'].numericValue,
                  'speed-index': report.audits['speed-index'].numericValue,
                  'largest-contentful-paint': report.audits['largest-contentful-paint'].numericValue,
                  'interactive': report.audits['interactive'].numericValue,
                  'total-blocking-time': report.audits['total-blocking-time'].numericValue,
                  'cumulative-layout-shift': report.audits['cumulative-layout-shift'].numericValue,
                }
              };
              
              // 确保历史文件目录存在
              const historyDir = path.dirname(historyFile);
              fs.ensureDirSync(historyDir);
              
              // 读取或创建历史记录文件
              let history = { entries: [] };
              if (fs.existsSync(historyFile)) {
                try {
                  history = fs.readJsonSync(historyFile);
                } catch (e) {
                  console.warn(`Warning: Could not parse history file, creating new one: ${e.message}`);
                }
              }
              
              // 确保有entries数组
              if (!history.entries) history.entries = [];
              
              // 添加新记录
              history.entries.push(metrics);
              
              // 保存更新的历史记录
              fs.writeJsonSync(historyFile, history, { spaces: 2 });
              
              console.log(`Successfully processed ${device} report and updated history.`);
              
            } catch (error) {
              console.error(`Error processing report: ${error.message}`);
              process.exit(1);
            }
            EOF
            echo "Created process-report.js file"
          fi
          
          # 检查目标报告文件是否存在
          DESKTOP_JSON="reports/$REPORT_DATE/$BRANCH_NAME/${{ matrix.site.name }}/lhr-${{ matrix.site.name }}-desktop.report.json"
          MOBILE_JSON="reports/$REPORT_DATE/$BRANCH_NAME/${{ matrix.site.name }}/lhr-${{ matrix.site.name }}-mobile.report.json"
          
          # 确保历史文件目录存在
          mkdir -p "reports"
          
          # 处理桌面端报告
          if [ -f "$DESKTOP_JSON" ]; then
            echo "Processing desktop report: $DESKTOP_JSON"
            node process-report.js "$DESKTOP_JSON" "reports/$BRANCH_NAME-history.json" "${{ matrix.site.url }}" "$REPORT_DATE" "desktop"
          else
            echo "Warning: Desktop report file not found: $DESKTOP_JSON"
          fi
          
          # 处理移动端报告
          if [ -f "$MOBILE_JSON" ]; then
            echo "Processing mobile report: $MOBILE_JSON"
            node process-report.js "$MOBILE_JSON" "reports/$BRANCH_NAME-history.json" "${{ matrix.site.url }}" "$REPORT_DATE" "mobile"
          else
            echo "Warning: Mobile report file not found: $MOBILE_JSON"
          fi
          
          # 创建网站列表已加速加载
          echo "Creating site list for quick loading"
          SITE_LIST_FILE="reports/$BRANCH_NAME-sites.json"
          if [ ! -f "$SITE_LIST_FILE" ]; then
            echo '{"sites":[]}' > "$SITE_LIST_FILE"
          fi
          
          # 使用jq将网站信息插入site列表
          apt-get update && apt-get install -y jq
          
          # 提取当前网站并检查是否已存在
          SITE_URL="${{ matrix.site.url }}"
          SITE_NAME="${{ matrix.site.name }}"
          
          # 如果网站不存在于列表中，则添加它
          if ! jq -e ".sites[] | select(.url == \"$SITE_URL\")" "$SITE_LIST_FILE" > /dev/null; then
            jq ".sites += [{\"url\": \"$SITE_URL\", \"name\": \"$SITE_NAME\"}]" "$SITE_LIST_FILE" > temp.json && mv temp.json "$SITE_LIST_FILE"
            echo "Added site $SITE_URL to site list"
          else
            echo "Site $SITE_URL already in site list"
          fi

      - name: List Reports Directory
        run: |
          echo "Contents of reports directory:"
          ls -la ./reports/
          echo "Contents of the latest report directory:"
          ls -la ./reports/$REPORT_DATE/$BRANCH_NAME/${{ matrix.site.name }}/

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          
          # 首先获取最新更改
          echo "Fetching latest changes..."
          git fetch origin
          
          # 处理未暂存文件，先将所有更改暂存再拉取
          echo "Stashing any changes before pull..."
          git stash -u || true
          
          # 拉取最新代码
          CURRENT_BRANCH=${GITHUB_REF#refs/heads/}
          git pull origin $CURRENT_BRANCH --ff-only || git pull origin $CURRENT_BRANCH
          
          # 如果有暂存的更改，恢复他们
          git stash pop || true
          
          # 添加所有报告文件和历史记录
          git add reports/
          git add .gitignore
          git add lighthouserc.json
          
          # 检查是否有更改需要提交
          if git diff --cached --quiet; then
            echo "No changes to commit"
            exit 0
          else
            git commit -m "Update Lighthouse reports $REPORT_DATE ($BRANCH_NAME ${{ matrix.site.name }})"
            git push origin HEAD:$CURRENT_BRANCH
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}