name: Lighthouse CI
on:
  push:
    branches:
      - main
      - master
    paths-ignore:
      - 'reports/**'  # 忽略报告目录的更改，防止循环触发
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

# 添加权限配置
permissions:
  contents: write
  pages: write

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # 更新到 Node.js 18

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y wget gnupg2
          wget -q https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt-get install -y ./google-chrome-stable_current_amd64.deb
          google-chrome --version

      - name: Install dependencies
        run: |
          npm init -y
          npm install -g @lhci/cli@0.12.x
          echo "node_modules/" > .gitignore
          echo ".lighthouseci/" >> .gitignore
          echo "*.deb" >> .gitignore

      - name: Run Lighthouse and Process Reports
        run: |
          mkdir -p reports
          NOW=$(date -u +"%Y-%m-%dT%H:%M:%S")
          
          # 运行桌面版测试
          echo "Running Desktop test..."
          lhci collect \
            --url https://www.fadada.com \
            --settings.preset=desktop \
            --settings.chromeFlags="--no-sandbox --headless=new --disable-gpu" \
            --settings.maxWaitForLoad=30000 \
            --output=json \
            --outDir=./reports \
            --numberOfRuns=1

          # 运行移动版测试
          echo "Running Mobile test..."
          lhci collect \
            --url https://www.fadada.com \
            --settings.formFactor=mobile \
            --settings.screenEmulation.mobile=true \
            --settings.screenEmulation.width=360 \
            --settings.screenEmulation.height=640 \
            --settings.screenEmulation.deviceScaleFactor=2 \
            --settings.chromeFlags="--no-sandbox --headless=new --disable-gpu" \
            --settings.maxWaitForLoad=30000 \
            --output=json \
            --outDir=./reports \
            --numberOfRuns=1

          echo "Moving Lighthouse results to reports directory:"
          mv .lighthouseci/*.json ./reports/ || true
          
          # 处理最新的桌面版和移动版报告
          LATEST_DESKTOP=$(find ./reports -name "lhr-*desktop*.json" -type f -printf '%T@ %p\n' | sort -n | tail -1 | cut -f2- -d" ")
          LATEST_MOBILE=$(find ./reports -name "lhr-*mobile*.json" -type f -printf '%T@ %p\n' | sort -n | tail -1 | cut -f2- -d" ")

          if [ -n "$LATEST_DESKTOP" ]; then
            echo "Processing desktop report: $LATEST_DESKTOP"
            DEVICE_TYPE=desktop DATE_WITH_TIME=$NOW node process-report.js "$LATEST_DESKTOP"
          fi

          if [ -n "$LATEST_MOBILE" ]; then
            echo "Processing mobile report: $LATEST_MOBILE"
            DEVICE_TYPE=mobile DATE_WITH_TIME=$NOW node process-report.js "$LATEST_MOBILE"
          fi

          # 清理多余的原始报告
          find ./reports -name "lhr-*.json" ! -name "$(basename $LATEST_DESKTOP)" ! -name "$(basename $LATEST_MOBILE)" -delete

      - name: List Reports Directory
        run: |
          echo "Contents of reports directory:"
          ls -la ./reports/

      - name: Cleanup and Prepare
        run: |
          rm -f google-chrome-stable_current_amd64.deb
          rm -rf .lighthouseci

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          
          # 添加所有JSON文件
          find reports -name "*.json" -exec git add {} \;
          git add .gitignore || true
          
          # 提交前检查文件状态
          git status
          
          git diff --staged --quiet || git commit -m "Update Lighthouse report $(date -u)"
          git push origin HEAD:${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}