name: Lighthouse CI
on:
  schedule:
    - cron: '0 */6 * * *'  # 每6小时运行一次
  workflow_dispatch:

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          npm install -g @lhci/cli
          npm install fs path

      - name: Run Lighthouse and Process Reports
        run: |
          # 设置脚本权限
          chmod +x process-report.js
          
          # 获取当前时间
          NOW=$(date -u +"%Y-%m-%dT%H:%M:%S")
          
          # 运行 Lighthouse 并收集报告
          lhci collect \
            --url https://www.fadada.com \
            --settings.preset=desktop \
            --settings.throttling.cpuSlowdownMultiplier=1 \
            --settings.chromeFlags="--no-sandbox --headless" \
            --output=json \
            --outDir=./reports
          
          # 处理生成的报告
          for f in ./reports/lighthouse-*.json; do
            if [ -f "$f" ]; then
              echo "Processing report: $f"
              DATE_WITH_TIME=$NOW node process-report.js "$f"
            fi
          done

      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add reports/
          git commit -m "Update Lighthouse report $(date -u)"
          git push