name: Run Lighthouse CI

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *' # 每天凌晨 3 点自动运行

# 添加权限设置
permissions:
  contents: write # 授予写入仓库内容的权限

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        site:
          - url: 'https://www.fadada.com'
            name: '法大大官网'
            device: 'mobile'
          - url: 'https://www.fadada.com'
            name: '法大大官网 (PC)'
            device: 'desktop'
          # 要添加更多网站，请复制上面两行并修改值
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Run Lighthouse CI on ${{ matrix.site.name }}
        id: lighthouse
        uses: treosh/lighthouse-ci-action@v9
        with:
          urls: '${{ matrix.site.url }}'
          configPath: '.lighthouserc.json'
          chromeFlags: '--no-sandbox --disable-dev-shm-usage --disable-gpu'
          settings: '{"emulatedFormFactor": "${{ matrix.site.device }}"}'
        continue-on-error: true # 即使lighthouse测试失败也继续执行后续步骤

      - name: Debug Lighthouse Output
        run: |
          echo "============ Lighthouse Debug Info ============"
          echo "Lighthouse links content:"
          echo "$LIGHTHOUSE_LINKS" | jq '.' || echo "无法解析LIGHTHOUSE_LINKS"
          echo "Lighthouse manifest content:"
          echo "$LIGHTHOUSE_MANIFEST" | jq '.' || echo "无法解析LIGHTHOUSE_MANIFEST"
          echo "============ End Debug Info ============"
        env:
          LIGHTHOUSE_MANIFEST: ${{ steps.lighthouse.outputs.manifest }}
          LIGHTHOUSE_LINKS: ${{ steps.lighthouse.outputs.links }}
        continue-on-error: true # 即使调试命令失败也继续

      - name: Format and Save Report Data
        run: |
          mkdir -p reports
          DATE=$(date +%Y-%m-%d)
          SITE_NAME="${{ matrix.site.name }}"
          SITE_URL="${{ matrix.site.url }}"
          SITE_ID=$(echo "$SITE_URL" | sed 's/[^a-zA-Z0-9]/_/g')_${{ matrix.site.device }}
      
          # 检查 LIGHTHOUSE_LINKS 并提取 REPORT_URL
          if echo "$LIGHTHOUSE_LINKS" | jq -e 'type == "object"' > /dev/null; then
            REPORT_URL=$(echo "$LIGHTHOUSE_LINKS" | jq -r 'to_entries[0].value // ""')
          else
            REPORT_URL=""
          fi
      
          # 创建报告 JSON
          echo "{" > "reports/data-$SITE_ID-$DATE.json"
          echo "  \"date\": \"$DATE\"," >> "reports/data-$SITE_ID-$DATE.json"
          echo "  \"name\": \"$SITE_NAME\"," >> "reports/data-$SITE_ID-$DATE.json"
          echo "  \"url\": \"$SITE_URL\"," >> "reports/data-$SITE_ID-$DATE.json"
          echo "  \"performance\": $PERF," >> "reports/data-$SITE_ID-$DATE.json"
          echo "  \"accessibility\": $ACC," >> "reports/data-$SITE_ID-$DATE.json"
          echo "  \"best-practices\": $BP," >> "reports/data-$SITE_ID-$DATE.json"
          echo "  \"seo\": $SEO," >> "reports/data-$SITE_ID-$DATE.json"
          echo "  \"reportUrl\": \"$REPORT_URL\"," >> "reports/data-$SITE_ID-$DATE.json"
          echo "  \"detailedData\": $DETAILED_DATA" >> "reports/data-$SITE_ID-$DATE.json"
          echo "}" >> "reports/data-$SITE_ID-$DATE.json"
        env:
          LIGHTHOUSE_MANIFEST: ${{ steps.lighthouse.outputs.manifest }}
          LIGHTHOUSE_LINKS: ${{ steps.lighthouse.outputs.links }}

      - name: Update History
        run: |
          DATE=$(date +%Y-%m-%d)
          SITE_URL="${{ matrix.site.url }}"
          SITE_ID=$(echo "$SITE_URL" | sed 's/[^a-zA-Z0-9]/_/g')_${{ matrix.site.device }}

          # jq已在GitHub Actions环境中预装

          # 如果存在历史数据文件，则更新
          if [ -f "reports/history.json" ]; then
            # 添加新数据到历史记录
            jq --argjson newData "$(cat "reports/data-$SITE_ID-$DATE.json")" '.reports += [$newData]' reports/history.json > reports/history.json.tmp
            mv reports/history.json.tmp reports/history.json
          else
            # 创建新的历史记录文件
            echo "{\"reports\": [$(cat "reports/data-$SITE_ID-$DATE.json")]}" > reports/history.json
          fi

          echo "Report data saved to reports/data-$SITE_ID-$DATE.json and updated in reports/history.json"
          echo "History content:"
          cat reports/history.json

      - name: Commit and Push Report Data
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions@github.com'
          git add reports/
          git commit -m "Add Lighthouse report data for ${{ matrix.site.name }} ($(date +%Y-%m-%d))" || echo "No changes to commit"
          git push
